// Additional fields needed for ISDOC export
export const ISDOC_FIELDS = [
  // Invoice metadata
  {
    code: "invoice_number",
    name: "Číslo faktury",
    type: "string",
    llm_prompt: "invoice number (číslo faktury)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "variable_symbol",
    name: "Variabilní symbol",
    type: "string",
    llm_prompt: "variable symbol (variabilní symbol) - payment reference number",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "constant_symbol",
    name: "Konstantní symbol",
    type: "string",
    llm_prompt: "constant symbol (konstantní symbol) - bank payment code",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "specific_symbol",
    name: "Specifický symbol",
    type: "string",
    llm_prompt: "specific symbol (specifický symbol) - additional payment reference",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "payment_method",
    name: "Způsob platby",
    type: "string",
    llm_prompt: "payment method (forma úhrady) - e.g. Příkazem, Hotově, Kartou",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "due_date",
    name: "Datum splatnosti",
    type: "string",
    llm_prompt: "due date (datum splatnosti) in YYYY-MM-DD format",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "tax_date",
    name: "Datum zdanitelného plnění",
    type: "string",
    llm_prompt: "tax point date (datum uskutečnění zdanitelného plnění) in YYYY-MM-DD format",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  
  // Supplier information
  {
    code: "supplier_name",
    name: "Dodavatel",
    type: "string",
    llm_prompt: "supplier/seller company name (dodavatel)",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "supplier_address",
    name: "Adresa dodavatele",
    type: "string",
    llm_prompt: "supplier full address including street, city, postal code",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "supplier_ic",
    name: "IČO dodavatele",
    type: "string",
    llm_prompt: "supplier company ID (IČ) - 8 digit number",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "supplier_dic",
    name: "DIČ dodavatele",
    type: "string",
    llm_prompt: "supplier tax ID (DIČ) - starts with CZ followed by IČ",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "supplier_bank_account",
    name: "Číslo účtu dodavatele",
    type: "string",
    llm_prompt: "supplier bank account number (číslo účtu)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "supplier_bank_code",
    name: "Kód banky dodavatele",
    type: "string",
    llm_prompt: "supplier bank code (kód banky) - 4 digit number after slash",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  
  // Customer information
  {
    code: "customer_name",
    name: "Odběratel",
    type: "string",
    llm_prompt: "customer/buyer company name (odběratel)",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "customer_address",
    name: "Adresa odběratele",
    type: "string",
    llm_prompt: "customer full address including street, city, postal code",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "customer_ic",
    name: "IČO odběratele",
    type: "string",
    llm_prompt: "customer company ID (IČ) - 8 digit number",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "customer_dic",
    name: "DIČ odběratele",
    type: "string",
    llm_prompt: "customer tax ID (DIČ) - starts with CZ followed by IČ",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  
  // Line items - stored as JSON
  {
    code: "line_items",
    name: "Položky faktury",
    type: "string", // Will store JSON array
    llm_prompt: "detailed line items as JSON array with fields: code, description, quantity, unit, unit_price, total, vat_rate, vat_amount",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  
  // Totals
  {
    code: "total_without_vat",
    name: "Základ bez DPH",
    type: "number",
    llm_prompt: "total amount without VAT (základ)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "total_vat_base",
    name: "Základ DPH",
    type: "string", // Will store JSON object with VAT breakdown
    llm_prompt: "VAT base amounts by rate as JSON object, e.g. {\"0\": 1000, \"12\": 2000, \"21\": 3000}",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "total_vat_amounts",
    name: "Součet DPH",
    type: "string", // Will store JSON object with VAT amounts
    llm_prompt: "VAT amounts by rate as JSON object, e.g. {\"0\": 0, \"12\": 240, \"21\": 630}",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  
  // Additional info
  {
    code: "order_number",
    name: "Číslo objednávky",
    type: "string",
    llm_prompt: "order number (číslo objednávky) if present",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "delivery_note_number",
    name: "Číslo dodacího listu",
    type: "string",
    llm_prompt: "delivery note number (číslo dodacího listu) if present",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "notes",
    name: "Poznámky",
    type: "string",
    llm_prompt: "any additional notes or legal text on the invoice",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
]
